package mapreduce

import (
	"encoding/json"
	"hash/fnv"
	"log"
	"os"
)

func doMap(
	jobName string, // the name of the MapReduce job
	mapTask int, // which map task this is
	inFile string,
	nReduce int, // the number of reduce task that will be run ("R" in the paper)
	mapF func(filename string, contents string) []KeyValue) {
	//
	// doMap manages one map task: it should read one of the input files
	// (inFile), call the user-defined map function (mapF) for that file's
	// contents, and partition mapF's output into nReduce intermediate files.
	//
	// There is one intermediate file per reduce task. The file name
	// includes both the map task number and the reduce task number. Use
	// the filename generated by reduceName(jobName, mapTask, r)
	// as the intermediate file for reduce task r. Call ihash() (see
	// below) on each key, mod nReduce, to pick r for a key/value pair.
	//
	// mapF() is the map function provided by the application. The first
	// argument should be the input file name, though the map function
	// typically ignores it. The second argument should be the entire
	// input file contents. mapF() returns a slice containing the
	// key/value pairs for reduce; see common.go for the definition of
	// KeyValue.
	//
	// Look at Go's ioutil and os packages for functions to read
	// and write files.
	//
	// Coming up with a scheme for how to format the key/value pairs on
	// disk can be tricky, especially when taking into account that both
	// keys and values could contain newlines, quotes, and any other
	// character you can think of.
	//
	// One format often used for serializing data to a byte stream that the
	// other end can correctly reconstruct is JSON. You are not required to
	// use JSON, but as the output of the reduce tasks *must* be JSON,
	// familiarizing yourself with it here may prove useful. You can write
	// out a data structure as a JSON string to a file using the commented
	// code below. The corresponding decoding functions can be found in
	// common_reduce.go.
	//
	//   enc := json.NewEncoder(file)
	//   for _, kv := ... {
	//     err := enc.Encode(&kv)
	//
	// Remember to close the file after you have written all the values!
	//
	// Your code here (Part I).




	//	copyright  by  sjt@hnu.edu.cn

	// openfile
	inputFile , err := os.Open(inFile)

	if err != nil {
		log.Fatalln("doMap : open file failure " ,err)

	}
	//close file
	defer inputFile.Close()

	// read fileInfo
	fileInfo , err := inputFile.Stat()

	if err != nil{
		log.Fatalln("daMap : getState failure " ,err )

	}

	//create  byte slice  to  prepare  for  Reading  inputFile  and  Writing  inputFile to this byte slice
	data := make([]byte, fileInfo.Size() )
	//ignore  returned  first variable(n bytes which are  bytes of inputFile )
	//Read  inputFile and Write data of inputFile into data variable
	_,err = inputFile.Read(data)

	//read err
	if err != nil {
		log.Fatalln("doMap : Read inputFile failure ",err)

	}


	//recall  mapF

	KeyValues  := mapF(fileInfo.Name(), string(data))


	//create  nReduce  intermediate  files
	for i := 0 ; i<nReduce ; i++ {
		filename := reduceName(jobName,mapTask,i)
		//create a new empty  file  called  filename
		reduceFile , err := os.Create(filename)
		if err != nil {
			log.Fatalln("doMap : reduceFile create failure " ,err)
		}

		defer  reduceFile.Close()

		enc := json.NewEncoder(reduceFile)
		// ignore  index of  k-v array
		// pick right k-v
		for _ , kv  :=  range KeyValues {

			// pick right k-v for specific  reduceFile
			//%nReduce =  0 , 1 ,... ,nReduce -1
			if ihash(kv.Key)%(nReduce) == i {

				err := enc.Encode(&kv)
				if err != nil {
					log.Fatalln("doMap: encode kv failure " ,err)
				}
			}

		}


	}











}

func ihash(s string) int {
	h := fnv.New32a()
	h.Write([]byte(s))
	return int(h.Sum32() & 0x7fffffff)
}
